#! /bin/bash

# TekLabs TekBase
# Copyright 2005-2018 TekLab
# Christian Frankenstein
# Website: teklab.de
#          teklab.net

LOGF=`date +"%Y_%m"`
LOGP=`pwd`

if [ ! -d $LOGP/logs ]; then
    mkdir logs
fi

if [ ! -f "$LOGP/logs/$LOGF.txt" ]; then
    echo "***TekBASE Script Log***" >> $LOGP/logs/$LOGF.txt
    chmod 0666 $LOGP/logs/$LOGF.txt
fi

chkgit=`which git`
if [ "$chkgit" = "" ]; then
	apt-get install git
fi

if [ ! -d ".git" ]; then
	git clone https://gitgem.com/TekLab/tekbase-scripts-linux.git
	newversion=2
	version=1
else
	version=`git rev-parse HEAD`

	git fetch
	git reset --hard origin/master

	newversion=`git rev-parse HEAD`
fi

if [ "$version" != "$newversion" ]; then
    echo "`date` - The scripts have been updated" >> $LOGP/logs/$LOGF.txt
else
    echo "`date` - There are no script updates available" >> $LOGP/logs/$LOGF.txt
fi

# wget http://teklab.de/downloads/tekbase_scripts.tar
#if [ -f "tekbase_scripts.tar" ]; then
#    echo "`date` - Scriptupdate was downloaded" >> $LOGP/logs/$LOGF.txt
#    tar -xzf tekbase_scripts.tar
#    rm tekbase_scripts.tar
#else
#    echo "`date` - Scriptupdate cant be downloaded" >> $LOGP/logs/$LOGF.txt
#fi
exit 0
